apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-generator
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /home/cluster
