apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app-editor
  namespace: edit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pv-app-editor
