apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app-generator
  namespace: gen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pv-app-generator
